# Generated by Django 5.1.4 on 2025-01-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20'), ('XRP', 'Ripple'), ('SOL', 'Solana')], max_length=20)),
                ('network', models.CharField(choices=[('BITCOIN', 'Bitcoin'), ('TRC20', 'Tron TRC20'), ('ERC20', 'Ethereum ERC20'), ('XRP', 'Ripple'), ('SOLANA', 'Solana')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crypto Address',
                'verbose_name_plural': 'Crypto Addresses',
            },
        ),
    ]
