# Generated by Django 5.1.4 on 2025-01-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cryptoaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoaddress',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20'), ('XRP', 'Ripple'), ('SOL', 'Solana')], max_length=20, unique=True),
        ),
    ]
